package com.ssm.mybatis.entity;

public class videoMove {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_move.video_id
     *
     * @mbggenerated Tue Nov 22 14:32:16 CST 2022
     */
    private Integer videoId;

    @Override
    public String toString() {
        return "videoMove{" +
                "videoId=" + videoId +
                ", videoName='" + videoName + '\'' +
                ", typeId=" + typeId +
                ", videoType='" + videoType + '\'' +
                ", playUrl='" + playUrl + '\'' +
                ", introduce='" + introduce + '\'' +
                ", state='" + state + '\'' +
                ", year='" + year + '\'' +
                '}';
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_move.video_name
     *
     * @mbggenerated Tue Nov 22 14:32:16 CST 2022
     */
    private String videoName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_move.type_id
     *
     * @mbggenerated Tue Nov 22 14:32:16 CST 2022
     */
    private Integer typeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_move.video_type
     *
     * @mbggenerated Tue Nov 22 14:32:16 CST 2022
     */
    private String videoType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_move.play_url
     *
     * @mbggenerated Tue Nov 22 14:32:16 CST 2022
     */
    private String playUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_move.introduce
     *
     * @mbggenerated Tue Nov 22 14:32:16 CST 2022
     */
    private String introduce;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_move.state
     *
     * @mbggenerated Tue Nov 22 14:32:16 CST 2022
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_move.year
     *
     * @mbggenerated Tue Nov 22 14:32:16 CST 2022
     */
    private String year;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_move.video_id
     *
     * @return the value of video_move.video_id
     *
     * @mbggenerated Tue Nov 22 14:32:16 CST 2022
     */
    public Integer getVideoId() {
        return videoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_move.video_id
     *
     * @param videoId the value for video_move.video_id
     *
     * @mbggenerated Tue Nov 22 14:32:16 CST 2022
     */
    public void setVideoId(Integer videoId) {
        this.videoId = videoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_move.video_name
     *
     * @return the value of video_move.video_name
     *
     * @mbggenerated Tue Nov 22 14:32:16 CST 2022
     */
    public String getVideoName() {
        return videoName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_move.video_name
     *
     * @param videoName the value for video_move.video_name
     *
     * @mbggenerated Tue Nov 22 14:32:16 CST 2022
     */
    public void setVideoName(String videoName) {
        this.videoName = videoName == null ? null : videoName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_move.type_id
     *
     * @return the value of video_move.type_id
     *
     * @mbggenerated Tue Nov 22 14:32:16 CST 2022
     */
    public Integer getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_move.type_id
     *
     * @param typeId the value for video_move.type_id
     *
     * @mbggenerated Tue Nov 22 14:32:16 CST 2022
     */
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_move.video_type
     *
     * @return the value of video_move.video_type
     *
     * @mbggenerated Tue Nov 22 14:32:16 CST 2022
     */
    public String getVideoType() {
        return videoType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_move.video_type
     *
     * @param videoType the value for video_move.video_type
     *
     * @mbggenerated Tue Nov 22 14:32:16 CST 2022
     */
    public void setVideoType(String videoType) {
        this.videoType = videoType == null ? null : videoType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_move.play_url
     *
     * @return the value of video_move.play_url
     *
     * @mbggenerated Tue Nov 22 14:32:16 CST 2022
     */
    public String getPlayUrl() {
        return playUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_move.play_url
     *
     * @param playUrl the value for video_move.play_url
     *
     * @mbggenerated Tue Nov 22 14:32:16 CST 2022
     */
    public void setPlayUrl(String playUrl) {
        this.playUrl = playUrl == null ? null : playUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_move.introduce
     *
     * @return the value of video_move.introduce
     *
     * @mbggenerated Tue Nov 22 14:32:16 CST 2022
     */
    public String getIntroduce() {
        return introduce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_move.introduce
     *
     * @param introduce the value for video_move.introduce
     *
     * @mbggenerated Tue Nov 22 14:32:16 CST 2022
     */
    public void setIntroduce(String introduce) {
        this.introduce = introduce == null ? null : introduce.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_move.state
     *
     * @return the value of video_move.state
     *
     * @mbggenerated Tue Nov 22 14:32:16 CST 2022
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_move.state
     *
     * @param state the value for video_move.state
     *
     * @mbggenerated Tue Nov 22 14:32:16 CST 2022
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_move.year
     *
     * @return the value of video_move.year
     *
     * @mbggenerated Tue Nov 22 14:32:16 CST 2022
     */
    public String getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_move.year
     *
     * @param year the value for video_move.year
     *
     * @mbggenerated Tue Nov 22 14:32:16 CST 2022
     */
    public void setYear(String year) {
        this.year = year == null ? null : year.trim();
    }
}
