package com.ssm.mybatis.mapper;

import com.ssm.mybatis.entity.videoMove;
import com.ssm.mybatis.entity.videoMoveExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface videoMoveMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_move
     *
     * @mbggenerated Tue Nov 22 14:32:16 CST 2022
     */
    int countByExample(videoMoveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_move
     *
     * @mbggenerated Tue Nov 22 14:32:16 CST 2022
     */
    int deleteByExample(videoMoveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_move
     *
     * @mbggenerated Tue Nov 22 14:32:16 CST 2022
     */
    int deleteByPrimaryKey(Integer videoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_move
     *
     * @mbggenerated Tue Nov 22 14:32:16 CST 2022
     */
    int insert(videoMove record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_move
     *
     * @mbggenerated Tue Nov 22 14:32:16 CST 2022
     */
    int insertSelective(videoMove record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_move
     *
     * @mbggenerated Tue Nov 22 14:32:16 CST 2022
     */
    List<videoMove> selectByExample(videoMoveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_move
     *
     * @mbggenerated Tue Nov 22 14:32:16 CST 2022
     */
    videoMove selectByPrimaryKey(Integer videoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_move
     *
     * @mbggenerated Tue Nov 22 14:32:16 CST 2022
     */
    int updateByExampleSelective(@Param("record") videoMove record, @Param("example") videoMoveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_move
     *
     * @mbggenerated Tue Nov 22 14:32:16 CST 2022
     */
    int updateByExample(@Param("record") videoMove record, @Param("example") videoMoveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_move
     *
     * @mbggenerated Tue Nov 22 14:32:16 CST 2022
     */
    int updateByPrimaryKeySelective(videoMove record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_move
     *
     * @mbggenerated Tue Nov 22 14:32:16 CST 2022
     */
    int updateByPrimaryKey(videoMove record);
}
